version: '3'

services:

  frontend:
    build: ./frontend
    image: rzultepapaje-frontend:latest
    container_name: rzultepapaje-frontend
    env_file: .env
    environment:
      - REACT_APP_API_ROOT=http://localhost:8000
    volumes:
      - ${PWD}/.env:/usr/src/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend


  backend:
    build: ./backend
    image: rzultepapaje-backend:latest
    container_name: rzultepapaje-backend
    env_file: .env  
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    container_name: rzultepapaje-database
    env_file: .env
    ports:
      - 5430:5432
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}


networks:
  default: