# Generated by Django 4.0.6 on 2023-01-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_column='No', max_length=20)),
                ('effective_date', models.DateField(db_column='Effective Date')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=20, null=True)),
                ('code', models.CharField(db_column='Code', max_length=5)),
                ('mid', models.DecimalField(db_column='Mid', decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'tabela_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelaB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_column='No', max_length=20)),
                ('effective_date', models.DateField(db_column='Effective Date')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=40, null=True)),
                ('code', models.CharField(db_column='Code', max_length=5)),
                ('mid', models.DecimalField(db_column='Mid', decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'tabela_b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelaC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_column='No', max_length=20)),
                ('trading_date', models.DateField(db_column='Trading Date')),
                ('effective_date', models.DateField(db_column='Effective Date')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=40, null=True)),
                ('code', models.CharField(db_column='Code', max_length=5)),
                ('bid', models.DecimalField(db_column='Bid', decimal_places=6, max_digits=10)),
                ('ask', models.DecimalField(db_column='Ask', decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'tabela_c',
                'managed': False,
            },
        ),
    ]
